import { describe, expect, it } from 'vitest'
import { promptOf } from './thread'

describe('promptOf', () => {
  it('should take what the human typed as their prompt', () => {
    expect(promptOf('fix the build')).toEqual({ kind: 'prompt', text: 'fix the build' })
  })

  it('should show a slash command the human ran, with its arguments, as the prompt', () => {
    const echo =
      '<command-message>review</command-message>\n<command-name>/review</command-name>\n<command-args>123 now</command-args>'

    expect(promptOf(echo)).toEqual({ kind: 'prompt', text: '`/review 123 now`' })
  })

  it('should show a slash command with no arguments as just its name', () => {
    expect(promptOf('<command-name>/compact</command-name>')).toEqual({ kind: 'prompt', text: '`/compact`' })
  })

  it('should take the first line of what the harness wrote, without its markup, as a harness line', () => {
    expect(promptOf('<local-command-stdout>Compacted\nmore</local-command-stdout>')).toEqual({
      kind: 'harness',
      line: 'Compacted',
    })
  })

  it('should have no harness line where the harness message holds only markup', () => {
    expect(promptOf('<local-command-stdout></local-command-stdout>')).toEqual({ kind: 'harness', line: null })
  })

  it('should read a caveat or an interruption as the harness too', () => {
    expect(promptOf('Caveat: the messages below were generated by the user')).toMatchObject({ kind: 'harness' })
    expect(promptOf('[Request interrupted by user]')).toEqual({
      kind: 'harness',
      line: '[Request interrupted by user]',
    })
  })
})
